export const REGIONAL_DEVELOPMENT_GRANT = 250_000;
export const REGIONAL_DEVELOPMENT_GRANT_REFERENCE =
  'regional-development-grant:v1';
export const PREFAB_ACCESS_LINK_ALLOWANCE = 36_000;
export const PREFAB_EXTENSION_OPERATING_RESERVE = 20_000;
export const MAX_PREFAB_EXTENSION_WITNESS_COST =
  REGIONAL_DEVELOPMENT_GRANT
  - PREFAB_ACCESS_LINK_ALLOWANCE
  - PREFAB_EXTENSION_OPERATING_RESERVE;
