export const REGIONAL_DEVELOPMENT_GRANT = 250_000;
export const REGIONAL_DEVELOPMENT_GRANT_REFERENCE =
  'regional-development-grant:v1';
export const MAX_STARTER_CORRIDOR_COST = 400_000;
export const MAX_CEMENT_SUPPLY_LINK_COST = 180_000;
export const MAX_REGIONAL_CONSTRUCTION_LINK_COST = 60_000;
export const MAX_REGIONAL_PAIR_ANALYSES = 32;
export const REFERENCE_SPEED_WORLD_UNITS_PER_TICK = 20;
export const REFERENCE_MANOEUVRE_TICKS = 60;
export const MAX_STEEL_REFERENCE_ACTIVE_TICKS = 1_599;
export const MAX_MODULE_REFERENCE_ACTIVE_TICKS = 1_060;
export const PREFAB_ACCESS_LINK_ALLOWANCE = 36_000;
export const PREFAB_EXTENSION_OPERATING_RESERVE = 20_000;
export const MAX_PREFAB_EXTENSION_WITNESS_COST =
  REGIONAL_DEVELOPMENT_GRANT
  - PREFAB_ACCESS_LINK_ALLOWANCE
  - PREFAB_EXTENSION_OPERATING_RESERVE;
