const TRAIN_REAL_MASS_KG = 180_000;
const TRAIN_MAX_ACCELERATION_MPS2 = 0.75;
const TRAIN_SIM_MASS_SCALE = 1 / 180;
const TRAIN_SIM_FORCE_SCALE = 2.6e-6;

export const GameConfig = {
  DEBUG: false,
  RESOLUTION: { WIDTH: 1920, HEIGHT: 1080 },
  CAMERA: { MIN_ZOOM: 0.1, MAX_ZOOM: 2.0, ZOOM_AMOUNT: 0.03, ACCELERATION: 0.06, DRAG: 0.0015, MAX_SPEED: 3.0 },
  PHYSICS: { GRAVITY_Y: 0, FRICTION_AIR: 0.015 },
  TRAIN: {
    REALISTIC_MASS_KG: TRAIN_REAL_MASS_KG,
    MAX_ACCELERATION_MPS2: TRAIN_MAX_ACCELERATION_MPS2,
    DEFAULT_MASS: TRAIN_REAL_MASS_KG * TRAIN_SIM_MASS_SCALE,
    ENGINE_POWER: TRAIN_REAL_MASS_KG * TRAIN_MAX_ACCELERATION_MPS2 * TRAIN_SIM_FORCE_SCALE,
    SCALE_X: 0.15,
    SCALE_Y: 0.15,
    DERAIL_SCALE: 0.4,
  },
  TRACK: { RAIL_TRACK_WIDTH: 866 * 0.85, SCALE: 0.05, MAX_CLOSE_DISTANCE: 100 },
  JUNCTION: { LENGTH: 400, LEFT_ANGLE_DEG: -15, RIGHT_ANGLE_DEG: 15 },
  FORCE: { GUIDE_CONSTANT: 0.002 },
  PID: { KP: 0.5, KI: 0.0, KD: 0.3 },
  GENERATION: {
    MAIN: { SECTIONS: 4, MIN_LENGTH: 400, MAX_LENGTH: 800, CURVE_PROB: 0.4, MIN_ANGLE: 15, MAX_ANGLE: 45, SMOOTHNESS: 0.8 },
    BRANCH: { SECTIONS: 4, MIN_LENGTH: 300, MAX_LENGTH: 600, CURVE_PROB: 0.6, MIN_ANGLE: 20, MAX_ANGLE: 60, SMOOTHNESS: 0.7 }
  },
  AUDIO: { BGM_VOLUME: 0.5, SFX_VOLUME: 0.8 },
  SAVE_KEY: 'rail-sim-save',
  WORLD: {
    CHUNK_SIZE: 4096,
    MAX_UNDO_STEPS: 50,
    SNAP_GRID_SIZE: 50,
    MAX_CURVE_TOLERANCE_DEG: 60,
    WORLDS_SAVE_KEY: 'rail-sim-worlds',
    AUTO_SAVE_INTERVAL_SECS: 60,
  },
  TOOLS: {
    COMPLETER_SEARCH_BUDGET: 2000,
    JUNCTION_OPTIMISATION_ITERATIONS: 200,
    JUNCTION_SAMPLE_POINTS: 40,
    COMPLETER_SAMPLE_RESOLUTION: 20,
    GHOST_ALPHA: 0.4,
  },
} as const;
